server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/mydb
    username: postgres
    password: '123Abc!@#'
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgresSQLDialect
